name: First Workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: U
    steps:
      - name: echo a string
        run: echo "Hello World Sudheesh"
      - name: Multiline Command
        run: |
          node -v
          npm -v
          ls -a
